var foto, titulo, precio, alt;
var regalos = [{
    foto:'sevilla.jpeg',
    alt: 'Sevilla',
    titulo: 'Tapas en Sevilla',
    precio:'750',
  },
  {
    foto: 'budapes.jpeg',
    alt: 'Foto Budapest',
    titulo: 'Degustacion de cervezas, Budapest',
    precio: '1200',
  },
  {
    foto: 'portugal.jpeg',
    alt: 'Cuevas Benagil',
    titulo: 'Aventura en kayak en Cuevas Benagil',
    precio: '1700',
  },
  {
    foto: 'auto.jpeg',
    alt: 'Foto auto',
    titulo: 'Viaje en Auto por la Toscana',
    precio: '2100',
  },
  {
    foto: 'buceo.jpeg',
    alt: 'Foto buceo',
    titulo: 'Buceo en Islas Azoles',
    precio: '2600',
  },
  {
    foto: 'terre.jpeg',
    alt: 'Foto cinque terre',
    titulo: 'Paseo en barco por Cinque Terre',
    precio: '2900',
  },
  {
    foto: 'jordania.jpeg',
    alt: 'Foto Jordania',
    titulo: 'Viaje por Petra, Jordania',
    precio: '3200',
  },
  {
    foto: 'paris.jpeg',
    alt: 'Foto Paris',
    titulo: 'Cena en la Tour Eiffel',
    precio: '3500',
  },
  {
    foto: 'hotel.jpeg',
    alt: 'Foto pileta',
    titulo: 'Estadia en Hotel Blanco, Formentera',
    precio: '4300',
  },
  {
    foto: 'playa.jpeg',
    alt: 'Foto playa',
    titulo: 'Dia de playa en Ibiza',
    precio: '4700',
  },
  {
    foto: 'otropais.jpeg',
    alt: 'Foto otropais',
    titulo: 'Excursion en Parque Suiza Bohemia',
    precio: '5300',
  },
  {
    foto: 'chocolate.jpeg',
    alt: 'Brujas',
    titulo: 'Entradas al Museo del chocolate, Brujas',
    precio: '5900',
  },
  {
    foto: 'amsterdam.jpeg',
    alt: 'amsterdam',
    titulo: 'Paseo por los canales de Amsterdam',
    precio: '7300',
  },
  {
    foto: 'londres.jpeg',
    alt: 'londres',
    titulo: 'Opera en el coliseo de Londres',
    precio: '8500',
  },
  {
    foto:'portofino.jpeg',
    alt: 'Portofino',
    titulo: 'Estadia en Portofino',
    precio:'9700',
  },
  {
    foto:'escocia.jpeg',
    alt: 'Escocia',
    titulo: 'Recorrido por los castillos de Escocia',
    precio:'10000',
  },
  {
    foto:'spa.jpg',
    alt: 'Spa',
    titulo: 'Spa en hotel',
    precio:'12500',
  },
  {
    foto:'capadocia.jpg',
    alt: 'Capadocia',
    titulo: 'Paseo en globo Capadocia',
    precio:'15000',
  },
  {
    foto:'alpes.jpg',
    alt: 'Alpes',
    titulo: 'Pases de sky en los Alpes',
    precio:'23000',
  },
];
